//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Svc.SvcSoap")]
    public interface SvcSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchCreditNoteByItem", ReplyAction="*")]
        test.Svc.PurchCreditNoteByItemResponse PurchCreditNoteByItem(test.Svc.PurchCreditNoteByItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchCreditNoteByItem", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.PurchCreditNoteByItemResponse> PurchCreditNoteByItemAsync(test.Svc.PurchCreditNoteByItemRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchPackingSlip", ReplyAction="*")]
        test.Svc.PurchPackingSlipResponse PurchPackingSlip(test.Svc.PurchPackingSlipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchPackingSlip", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.PurchPackingSlipResponse> PurchPackingSlipAsync(test.Svc.PurchPackingSlipRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvTransferJournal", ReplyAction="*")]
        test.Svc.InvTransferJournalResponse InvTransferJournal(test.Svc.InvTransferJournalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvTransferJournal", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.InvTransferJournalResponse> InvTransferJournalAsync(test.Svc.InvTransferJournalRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvMovementJournal", ReplyAction="*")]
        test.Svc.InvMovementJournalResponse InvMovementJournal(test.Svc.InvMovementJournalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvMovementJournal", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.InvMovementJournalResponse> InvMovementJournalAsync(test.Svc.InvMovementJournalRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesPackingSlip", ReplyAction="*")]
        test.Svc.SalesPackingSlipResponse SalesPackingSlip(test.Svc.SalesPackingSlipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesPackingSlip", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.SalesPackingSlipResponse> SalesPackingSlipAsync(test.Svc.SalesPackingSlipRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesCreditNote", ReplyAction="*")]
        test.Svc.SalesCreditNoteResponse SalesCreditNote(test.Svc.SalesCreditNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesCreditNote", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.SalesCreditNoteResponse> SalesCreditNoteAsync(test.Svc.SalesCreditNoteRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvCountJournal", ReplyAction="*")]
        test.Svc.InvCountJournalResponse InvCountJournal(test.Svc.InvCountJournalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvCountJournal", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.InvCountJournalResponse> InvCountJournalAsync(test.Svc.InvCountJournalRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        test.Svc.HelloWorldResponse HelloWorld(test.Svc.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<test.Svc.HelloWorldResponse> HelloWorldAsync(test.Svc.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchCreditNoteByItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchCreditNoteByItem", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.PurchCreditNoteByItemRequestBody Body;
        
        public PurchCreditNoteByItemRequest() {
        }
        
        public PurchCreditNoteByItemRequest(test.Svc.PurchCreditNoteByItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchCreditNoteByItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public PurchCreditNoteByItemRequestBody() {
        }
        
        public PurchCreditNoteByItemRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchCreditNoteByItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchCreditNoteByItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.PurchCreditNoteByItemResponseBody Body;
        
        public PurchCreditNoteByItemResponse() {
        }
        
        public PurchCreditNoteByItemResponse(test.Svc.PurchCreditNoteByItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchCreditNoteByItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PurchCreditNoteByItemResult;
        
        public PurchCreditNoteByItemResponseBody() {
        }
        
        public PurchCreditNoteByItemResponseBody(string PurchCreditNoteByItemResult) {
            this.PurchCreditNoteByItemResult = PurchCreditNoteByItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchPackingSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchPackingSlip", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.PurchPackingSlipRequestBody Body;
        
        public PurchPackingSlipRequest() {
        }
        
        public PurchPackingSlipRequest(test.Svc.PurchPackingSlipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchPackingSlipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public PurchPackingSlipRequestBody() {
        }
        
        public PurchPackingSlipRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchPackingSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchPackingSlipResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.PurchPackingSlipResponseBody Body;
        
        public PurchPackingSlipResponse() {
        }
        
        public PurchPackingSlipResponse(test.Svc.PurchPackingSlipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchPackingSlipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PurchPackingSlipResult;
        
        public PurchPackingSlipResponseBody() {
        }
        
        public PurchPackingSlipResponseBody(string PurchPackingSlipResult) {
            this.PurchPackingSlipResult = PurchPackingSlipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvTransferJournalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvTransferJournal", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.InvTransferJournalRequestBody Body;
        
        public InvTransferJournalRequest() {
        }
        
        public InvTransferJournalRequest(test.Svc.InvTransferJournalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvTransferJournalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public InvTransferJournalRequestBody() {
        }
        
        public InvTransferJournalRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvTransferJournalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvTransferJournalResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.InvTransferJournalResponseBody Body;
        
        public InvTransferJournalResponse() {
        }
        
        public InvTransferJournalResponse(test.Svc.InvTransferJournalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvTransferJournalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvTransferJournalResult;
        
        public InvTransferJournalResponseBody() {
        }
        
        public InvTransferJournalResponseBody(string InvTransferJournalResult) {
            this.InvTransferJournalResult = InvTransferJournalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvMovementJournalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvMovementJournal", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.InvMovementJournalRequestBody Body;
        
        public InvMovementJournalRequest() {
        }
        
        public InvMovementJournalRequest(test.Svc.InvMovementJournalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvMovementJournalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public InvMovementJournalRequestBody() {
        }
        
        public InvMovementJournalRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvMovementJournalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvMovementJournalResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.InvMovementJournalResponseBody Body;
        
        public InvMovementJournalResponse() {
        }
        
        public InvMovementJournalResponse(test.Svc.InvMovementJournalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvMovementJournalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvMovementJournalResult;
        
        public InvMovementJournalResponseBody() {
        }
        
        public InvMovementJournalResponseBody(string InvMovementJournalResult) {
            this.InvMovementJournalResult = InvMovementJournalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesPackingSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesPackingSlip", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.SalesPackingSlipRequestBody Body;
        
        public SalesPackingSlipRequest() {
        }
        
        public SalesPackingSlipRequest(test.Svc.SalesPackingSlipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesPackingSlipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public SalesPackingSlipRequestBody() {
        }
        
        public SalesPackingSlipRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesPackingSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesPackingSlipResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.SalesPackingSlipResponseBody Body;
        
        public SalesPackingSlipResponse() {
        }
        
        public SalesPackingSlipResponse(test.Svc.SalesPackingSlipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesPackingSlipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SalesPackingSlipResult;
        
        public SalesPackingSlipResponseBody() {
        }
        
        public SalesPackingSlipResponseBody(string SalesPackingSlipResult) {
            this.SalesPackingSlipResult = SalesPackingSlipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesCreditNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesCreditNote", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.SalesCreditNoteRequestBody Body;
        
        public SalesCreditNoteRequest() {
        }
        
        public SalesCreditNoteRequest(test.Svc.SalesCreditNoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesCreditNoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public SalesCreditNoteRequestBody() {
        }
        
        public SalesCreditNoteRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesCreditNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesCreditNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.SalesCreditNoteResponseBody Body;
        
        public SalesCreditNoteResponse() {
        }
        
        public SalesCreditNoteResponse(test.Svc.SalesCreditNoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesCreditNoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SalesCreditNoteResult;
        
        public SalesCreditNoteResponseBody() {
        }
        
        public SalesCreditNoteResponseBody(string SalesCreditNoteResult) {
            this.SalesCreditNoteResult = SalesCreditNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvCountJournalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvCountJournal", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.InvCountJournalRequestBody Body;
        
        public InvCountJournalRequest() {
        }
        
        public InvCountJournalRequest(test.Svc.InvCountJournalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvCountJournalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public InvCountJournalRequestBody() {
        }
        
        public InvCountJournalRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvCountJournalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvCountJournalResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.InvCountJournalResponseBody Body;
        
        public InvCountJournalResponse() {
        }
        
        public InvCountJournalResponse(test.Svc.InvCountJournalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvCountJournalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvCountJournalResult;
        
        public InvCountJournalResponseBody() {
        }
        
        public InvCountJournalResponseBody(string InvCountJournalResult) {
            this.InvCountJournalResult = InvCountJournalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(test.Svc.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.Svc.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(test.Svc.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SvcSoapChannel : test.Svc.SvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcSoapClient : System.ServiceModel.ClientBase<test.Svc.SvcSoap>, test.Svc.SvcSoap {
        
        public SvcSoapClient() {
        }
        
        public SvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.PurchCreditNoteByItemResponse test.Svc.SvcSoap.PurchCreditNoteByItem(test.Svc.PurchCreditNoteByItemRequest request) {
            return base.Channel.PurchCreditNoteByItem(request);
        }
        
        public string PurchCreditNoteByItem(string input) {
            test.Svc.PurchCreditNoteByItemRequest inValue = new test.Svc.PurchCreditNoteByItemRequest();
            inValue.Body = new test.Svc.PurchCreditNoteByItemRequestBody();
            inValue.Body.input = input;
            test.Svc.PurchCreditNoteByItemResponse retVal = ((test.Svc.SvcSoap)(this)).PurchCreditNoteByItem(inValue);
            return retVal.Body.PurchCreditNoteByItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.PurchCreditNoteByItemResponse> test.Svc.SvcSoap.PurchCreditNoteByItemAsync(test.Svc.PurchCreditNoteByItemRequest request) {
            return base.Channel.PurchCreditNoteByItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.PurchCreditNoteByItemResponse> PurchCreditNoteByItemAsync(string input) {
            test.Svc.PurchCreditNoteByItemRequest inValue = new test.Svc.PurchCreditNoteByItemRequest();
            inValue.Body = new test.Svc.PurchCreditNoteByItemRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).PurchCreditNoteByItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.PurchPackingSlipResponse test.Svc.SvcSoap.PurchPackingSlip(test.Svc.PurchPackingSlipRequest request) {
            return base.Channel.PurchPackingSlip(request);
        }
        
        public string PurchPackingSlip(string input) {
            test.Svc.PurchPackingSlipRequest inValue = new test.Svc.PurchPackingSlipRequest();
            inValue.Body = new test.Svc.PurchPackingSlipRequestBody();
            inValue.Body.input = input;
            test.Svc.PurchPackingSlipResponse retVal = ((test.Svc.SvcSoap)(this)).PurchPackingSlip(inValue);
            return retVal.Body.PurchPackingSlipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.PurchPackingSlipResponse> test.Svc.SvcSoap.PurchPackingSlipAsync(test.Svc.PurchPackingSlipRequest request) {
            return base.Channel.PurchPackingSlipAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.PurchPackingSlipResponse> PurchPackingSlipAsync(string input) {
            test.Svc.PurchPackingSlipRequest inValue = new test.Svc.PurchPackingSlipRequest();
            inValue.Body = new test.Svc.PurchPackingSlipRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).PurchPackingSlipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.InvTransferJournalResponse test.Svc.SvcSoap.InvTransferJournal(test.Svc.InvTransferJournalRequest request) {
            return base.Channel.InvTransferJournal(request);
        }
        
        public string InvTransferJournal(string input) {
            test.Svc.InvTransferJournalRequest inValue = new test.Svc.InvTransferJournalRequest();
            inValue.Body = new test.Svc.InvTransferJournalRequestBody();
            inValue.Body.input = input;
            test.Svc.InvTransferJournalResponse retVal = ((test.Svc.SvcSoap)(this)).InvTransferJournal(inValue);
            return retVal.Body.InvTransferJournalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.InvTransferJournalResponse> test.Svc.SvcSoap.InvTransferJournalAsync(test.Svc.InvTransferJournalRequest request) {
            return base.Channel.InvTransferJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.InvTransferJournalResponse> InvTransferJournalAsync(string input) {
            test.Svc.InvTransferJournalRequest inValue = new test.Svc.InvTransferJournalRequest();
            inValue.Body = new test.Svc.InvTransferJournalRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).InvTransferJournalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.InvMovementJournalResponse test.Svc.SvcSoap.InvMovementJournal(test.Svc.InvMovementJournalRequest request) {
            return base.Channel.InvMovementJournal(request);
        }
        
        public string InvMovementJournal(string input) {
            test.Svc.InvMovementJournalRequest inValue = new test.Svc.InvMovementJournalRequest();
            inValue.Body = new test.Svc.InvMovementJournalRequestBody();
            inValue.Body.input = input;
            test.Svc.InvMovementJournalResponse retVal = ((test.Svc.SvcSoap)(this)).InvMovementJournal(inValue);
            return retVal.Body.InvMovementJournalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.InvMovementJournalResponse> test.Svc.SvcSoap.InvMovementJournalAsync(test.Svc.InvMovementJournalRequest request) {
            return base.Channel.InvMovementJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.InvMovementJournalResponse> InvMovementJournalAsync(string input) {
            test.Svc.InvMovementJournalRequest inValue = new test.Svc.InvMovementJournalRequest();
            inValue.Body = new test.Svc.InvMovementJournalRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).InvMovementJournalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.SalesPackingSlipResponse test.Svc.SvcSoap.SalesPackingSlip(test.Svc.SalesPackingSlipRequest request) {
            return base.Channel.SalesPackingSlip(request);
        }
        
        public string SalesPackingSlip(string input) {
            test.Svc.SalesPackingSlipRequest inValue = new test.Svc.SalesPackingSlipRequest();
            inValue.Body = new test.Svc.SalesPackingSlipRequestBody();
            inValue.Body.input = input;
            test.Svc.SalesPackingSlipResponse retVal = ((test.Svc.SvcSoap)(this)).SalesPackingSlip(inValue);
            return retVal.Body.SalesPackingSlipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.SalesPackingSlipResponse> test.Svc.SvcSoap.SalesPackingSlipAsync(test.Svc.SalesPackingSlipRequest request) {
            return base.Channel.SalesPackingSlipAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.SalesPackingSlipResponse> SalesPackingSlipAsync(string input) {
            test.Svc.SalesPackingSlipRequest inValue = new test.Svc.SalesPackingSlipRequest();
            inValue.Body = new test.Svc.SalesPackingSlipRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).SalesPackingSlipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.SalesCreditNoteResponse test.Svc.SvcSoap.SalesCreditNote(test.Svc.SalesCreditNoteRequest request) {
            return base.Channel.SalesCreditNote(request);
        }
        
        public string SalesCreditNote(string input) {
            test.Svc.SalesCreditNoteRequest inValue = new test.Svc.SalesCreditNoteRequest();
            inValue.Body = new test.Svc.SalesCreditNoteRequestBody();
            inValue.Body.input = input;
            test.Svc.SalesCreditNoteResponse retVal = ((test.Svc.SvcSoap)(this)).SalesCreditNote(inValue);
            return retVal.Body.SalesCreditNoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.SalesCreditNoteResponse> test.Svc.SvcSoap.SalesCreditNoteAsync(test.Svc.SalesCreditNoteRequest request) {
            return base.Channel.SalesCreditNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.SalesCreditNoteResponse> SalesCreditNoteAsync(string input) {
            test.Svc.SalesCreditNoteRequest inValue = new test.Svc.SalesCreditNoteRequest();
            inValue.Body = new test.Svc.SalesCreditNoteRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).SalesCreditNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.InvCountJournalResponse test.Svc.SvcSoap.InvCountJournal(test.Svc.InvCountJournalRequest request) {
            return base.Channel.InvCountJournal(request);
        }
        
        public string InvCountJournal(string input) {
            test.Svc.InvCountJournalRequest inValue = new test.Svc.InvCountJournalRequest();
            inValue.Body = new test.Svc.InvCountJournalRequestBody();
            inValue.Body.input = input;
            test.Svc.InvCountJournalResponse retVal = ((test.Svc.SvcSoap)(this)).InvCountJournal(inValue);
            return retVal.Body.InvCountJournalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.InvCountJournalResponse> test.Svc.SvcSoap.InvCountJournalAsync(test.Svc.InvCountJournalRequest request) {
            return base.Channel.InvCountJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.InvCountJournalResponse> InvCountJournalAsync(string input) {
            test.Svc.InvCountJournalRequest inValue = new test.Svc.InvCountJournalRequest();
            inValue.Body = new test.Svc.InvCountJournalRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).InvCountJournalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.Svc.HelloWorldResponse test.Svc.SvcSoap.HelloWorld(test.Svc.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string input) {
            test.Svc.HelloWorldRequest inValue = new test.Svc.HelloWorldRequest();
            inValue.Body = new test.Svc.HelloWorldRequestBody();
            inValue.Body.input = input;
            test.Svc.HelloWorldResponse retVal = ((test.Svc.SvcSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.Svc.HelloWorldResponse> test.Svc.SvcSoap.HelloWorldAsync(test.Svc.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.Svc.HelloWorldResponse> HelloWorldAsync(string input) {
            test.Svc.HelloWorldRequest inValue = new test.Svc.HelloWorldRequest();
            inValue.Body = new test.Svc.HelloWorldRequestBody();
            inValue.Body.input = input;
            return ((test.Svc.SvcSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
